# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 394b861eb5c2151a64337e272cfad451a1d9deb33453888219854792fe327797e7f544dfa672917adc7f6630fb71573a7d36314facfd53d858944b63295b8787

test:
  secret_key_base: cabda72a46da0139ebf4303317266a8b819947a904dcab174156872f3a408f0d3d037952aa93e29d16693ecb7913d267d26d3e5de5db001f0e4ca4e45b727fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
